#!/usr/bin/env bash

if [ -e /etc/shadow ]
then
  echo Shadow password is enable
fi

if [ -w /etc/shadow ]
then
  echo You have permission to edit /etc/shadow
else
  echo You do NOT have permission to edit /etc/shadow
fi
