#!/usr/bin/env bash
# Make gpg keys backup in two ways.
mkdir -p gpg_backup && cd gpg_backup

# Export each key.
gpg -armor --export douglasmg7@gmail.com > douglasmg7-public-gpg.key
gpg -armor --export zunka@zunka.com.br > zunka-public-gpg.key
gpg -armor --export-secret-keys douglasmg7@gmail.com > douglasmg7-secret-gpg.key
gpg --export-ownertrust > douglasmg7-ownertrust-gpg.txt

# Backup all folder.
tar -pczf gnupg.tar.gz ~/.gnupg &>/dev/null

echo "Backup was created into gpg_backup directory."

# To import each key.
# Import secret key (which contains the public key) and ownertrust.
# gpg --import douglasmg7-secret-gpg.key
# gpg --import-ownertrust douglasmg7-ownertrust-gpg.txt
