#!/usr/bin/env bash
# Make gpg keys backup in two ways.

# Backup all folder.
$ gpg -a --export douglasmg7@gmail.com > douglasmg7-public-gpg.key
$ gpg -a --export-secret-keys douglasmg7@gmail.com > douglasmg7-secret-gpg.key
$ gpg --export-ownertrust > chrisroos-ownertrust-gpg.txt

# Import secret key (which contains the public key) and ownertrust
$ gpg --import chrisroos-secret-gpg.key
$ gpg --import-ownertrust chrisroos-ownertrust-gpg.txt


# Export keys.
